### ISSUE TITLE
Preparing the repository and the startup files

### ISSUE THREAD

**Issue by FadiZahhar** [pro-freelancer/qpulse#1]
Upon the meeting on June 18 we agreed on the following.
1- prepare the repository and add the theme to it. you can check it on git hub at the following link. 
http://pro-freelancer.github.io/qpulse/

2- Meeting on Friday 3 July 2015 for project kick off.

3- Monday 6 start implementing the selected theme to Wordpress on qpulse.fr

4- Monday 13 should deliver a working solution and write a small end user documentation on how to use it on github wiki pages.

This issue ticket will be close on Monday 6 as an indicator that I start working on the project.

Regards,

**Comment by QPulse-Dima** [comment]
Should I sign up on github or will you give me credentials?

**Comment by FadiZahhar** [comment]
I already registered you.
you can sign in on http://www.github.com
username: your gmail account dima.abou.moussa@gmail.com
pass: P@ssword@123

click on watch tab once login you , you will notice pro-freelancer/qpulse project.
ps: you always can reply from email notification in case you don't feel like to use github.

Regards,

**Comment by QPulse-Dima** [comment]
Good morning fadi
I just called the auditor he prefers to wait till the company is officially
registered to proceed with the website because it's better to pay from the
capital to keep track of all payments.
Therefore I would like to postpone our kickoff meeting till after the bank
account is ready.
I'm sorry for the inconvenience. Will let you know as soon as I'm ready.
Regards

**Comment by FadiZahhar** [comment]
No Problem Dima,
whenever you are ready, we will set another week as a kick off.
I will reschedule the day upon my availability.

Regards,

**Comment by FadiZahhar** [comment]
2- Meeting on Thursday 27 August 2015 at 6:30pm for project kick off.

3- Monday 31 start implementing the selected theme to Wordpress on qpulse.fr

4- Monday 7 of September should deliver a working solution and write a small end user documentation on how to use it on github wiki pages.

This issue ticket will be close on Monday 31 of september as an indicator that I start working on the project.

PS: I just forget about the status, I reopened the ticket on git hug and as planed will continue with the steps.

To proceed, I need the following:
1- FTP: username and password of the (hosting). in case there is no FTP account, a cpanel account will do
2- the username and password of the wordpress back office to be able to activate the theme and add content on it.

Regards,

**Comment by FadiZahhar** [comment]
Started on Saturday 29 August and finished a first draft.
30 minutes and I will upload it online.

**Comment by QPulse-Dima** [comment]
Good morning Fadi, ya3tik el 3afye.
 Is it possible to meet today or tomorrow? If not, I please note the
following:
- Can we make the facebook and linkedin icons dark blue instead of purple?
- Can " Management consultancy" be written in the same color as the other
  titles?
- The title inside each section  has a mistake: consult_e_ncy should be
  consult_a_ncy
-  I noticed that the photos in the last 2 sections are inappropriate (the
  background especially)  (that's why the title is not very visible),
  attached are alternative photos for each section.
- Can we please change the subtitle of the section "writing consultancy"
  from (Projects assistance for students or graduates) into (SOP and project
  writing assistance)
- I also changed the content of the section "writing consultancy", you will
  find the changes attached
- Please remove the subtitles from the last 2 sections (i don't want any
  subtitles in the training section and the mystery shopping and audits
  section)
- Enter between MBA and info@qpulse.fr ( new line)

Thank you
Dima

##

**Comment by FadiZahhar** [comment]
ok great.  in case all changes are related to content, kindly reply that you like the concept of the website, so I can adopted to WordPress.

In this case you will have the freedom to : 
1.change any unwanted image, text color display, font (bold, italic, regular) paragraphs display (list content) and so on.
2. add as many you like new content.
3. Change content regurally.

In case all changes are related to content , kindly reply that you approved the concept so I can proceed with the WordPress theme development.

Regards
