### ISSUE TITLE
Qpulse First Draft Demo

### ISSUE THREAD

**Issue by FadiZahhar** [pro-freelancer/qpulse#2]
you can see the frist draft on:
http://www.pro-solutions.net/demos/qpulse/index.html
# concept of design #
## header

Logo at the top, beside an animated pulse.
navigation have color of the logo and hover of the pulse.

Each section is seprated as a blog.
you can check by order:
1. about, areas of experties, contact (since the data and images are nice choosen).
2. Projects (need to adopt the following in the future to have full potential in showing this section).
this section should have images of the companies you work with. once click to view more it should display all details of work that you did in the company. 
how it shows now ??? I adopt this false pattern, a concept of expertise and display the list of companies you work as concept of expertise.

between projects and areas of experties a block of information is displayed such you can find us on (social media) and contact info.

I adopt as much possible the latest HTML5 Responsive CSS3 smooth animations that are compatible with most browsers including mobile.

you can test the them on your mobile or minimize the screen to check how it will looks.

your feedback is appreciated  to proceed.

In case evrething is ok as concept will start implementing this theme to wordpress so you can modify  the content dynamically from wordpress.

Regards,

**Comment by QPulse-Dima** [comment]
Hi,
In general, I like the appearance of the website, thanks. I have the
following remarks:
- I don't want the the animated pulse because it implies that it's a
  medical equipment or heart equipment company
- Can we change the font of the text inside each section (eg. inside the
  who we are, inside the hospital accreditation, etc.)
- Please cancel the "Our projects" section or hide it if possible (I might
  add them later on when I have more projects). right now they will be
  integrated in the about section.
- I prefer if my name is not written outside, but only when one clicks on
  contact. also delete the "now" in " contact us now"
- When I open who we are, the window is too large for the content, I prefer
  it to be a box that fits the size of the contents, and that it opens with a
  square animation not a circle, and that after it opens, we can still see
  the page faded in the background.
  -The same applies to all other sections: Same animation when it opens i.e.
  square box and page faded in the background (I don't want the page to move
  or disappear)  (also I prefer the windows to be smaller and with a dark
  grey background if possible instead of white)
- I like the pics in the area of expertise section
- the titles in (mystery shopping & training and personal coaching) are not
  visible (color, font, etc..) maybe dark blue, bold,..?

I hope i was clear :) let me know if you need any clarifications

On Sat, Aug 29, 2015 at 8:11 PM, Fadi Nicolas Zahhar <
notifications@github.com> wrote:

> you can see the frist draft on:
> http://www.pro-solutions.net/demos/qpulse/index.html
> concept of design # header
> 
> Logo at the top, beside an animated pulse.
> navigation have color of the logo and hover of the pulse.
> 
> Each section is seprated as a blog.
> you can check by order:
> 1. about, areas of experties, contact (since the data and images are nice
> choosen).
> 2. Projects (need to adopt the following in the future to have full
> potential in showing this section).
> this section should have images of the companies you work with. once click
> to view more it should display all details of work that you did in the
> company.
> how it shows now ??? I adopt this false pattern, a concept of expertise
> and display the list of companies you work as concept of expertise.
> 
> between projects and areas of experties a block of information is
> displayed such you can find us on (social media) and contact info.
> 
> I adopt as much possible the latest HTML5 Responsive CSS3 smooth
> animations that are compatible with most browsers including mobile.
> 
> you can test the them on your mobile or minimize the screen to check how
> it will looks.
> 
> your feedback is appreciated to proceed.
> 
> In case evrething is ok as concept will start implementing this theme to
> wordpress so you can modify the content dynamically from wordpress.
> 
> Regards,
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pro-freelancer/qpulse/issues/2.

##

**Comment by FadiZahhar** [comment]
Well noted and clear. Will work on the changes and reply back once done.

**Comment by FadiZahhar** [comment]
here you go : 
http://www.pro-solutions.net/demos/qpulse/second/

kindly note the following : 
1. animated pulse removed.
2.  "Our projects" section is hidden right now they are  integrated in the about section.
3. your name is not written outside, but only when one clicks on
   contact. also deleted the "now" in " contact us now".
4. changes the box that fits the size of the contents, and that it opens with a
   square animation not a circle, and that after it opens, you can still see
   the page faded in the background also applied it to all other sections. Same animation when it opens  square box and page faded in the background (page do not move
   or disappear)  (a windows  is smaller and with a dark grey background).
5. the titles in (mystery shopping & training and personal coaching) are not
   visible (color, font, etc..) maybe dark blue, bold,..made them darker.

also kindly note the following facts : 
once the theme is adopted to wordpress you can do the following : 
1. Change the top navigation name , add, remove as you like.
2. Add sections same as design ( reusable components )
   example the effect of who we are, you can add as many with different title and different content in your page.
3. the follow us contact us also
4. the expertise area, can be reusable with many other sections such (projects, or any new sections that don't exist yet).
5. the capibility in the texteditor to add colomun based content, what I meant about that that could have diffrent type of content example.
6. image in the left, content in the right, or big image at the top and content at the bottom , or content at the left and image at the right, and this could be repeated and mixed as long as you have content in an article.

Hope I'm clear about the pattern of use of the template.
waiting for your feedback , and in case everything is OK, will start to implement the solution on wordpress theme.

PS: the mobile and tablet version is not tested to be bug free yet, this will be at the end of process after delivering a working back office , front end WordPress Theme.

Regards,

**Comment by FadiZahhar** [comment]
This ticket is closed, since a new ticket was opened.
